sudo: required
dist: trusty
cache:
  directories:
    - "node_modules"
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js
node_js:
  - "7"
before_install:
  - npm install -g cordova
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script: 
  - npm run e2e
  - chmod ugo+x scripts/run-ionic-cloud-builds-on-pr-or-master.sh
  - ./scripts/run-ionic-cloud-builds-on-pr-or-master.sh
